---
PIPE_PATH: ""
BINARIES_PATH: "" 
FIRMWARES_PATH: ""
OLD_LIBRARIES: ""
ORIGINAL_BMC: ""
ORIGINAL_BIOS: ""
COMPILE_URI: 
COMPILE_TCPPORT: ""
EM100BMC: 
EM100BIOS: 
IS_EMULATORS_POOL: ""
ACRONAME: ""
USB_STORAGE: "" 
DISTROS_PATH: ""
STORAGE_TCPPORT: "" 
STORAGE_URI: 
BMC_SERIAL: ""
EM100_DEVID: ""
