name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    
    - name: fmt check
      uses: Jerome1337/gofmt-action@v1.0.4
      with:
        gofmt-path: './'
        gofmt-flags: '-l -d'

    - name: lint check
      uses: Jerome1337/golint-action@v1.0.2
      with:
        golint-path: './...'